#!/usr/bin/env python3

# -------------------
# DEPENDENCIES
# -------------------

import sys
import subprocess
import argparse
from pathlib import Path


# -----------------------------
# MAIN ENTRY POINT
# -----------------------------

if __name__ == '__main__':
    # -----------------------------
    # PARSE COMMAND-LINE ARGUMENTS
    # -----------------------------
    parser = argparse.ArgumentParser(
        description='rpsHunter: A tool for gene domain identification and analysis.'
    )

    parser.add_argument(
        '--setup-databases',
        action='store_true',
        help="Downloads and sets up CDD and rpsbproc annotation databases."
    )

    parser.add_argument(
        '--download-genomes',
        action='store_true',
        help="Downloads genomes specified in .yaml file. "
             "Will skip download if the same files exist currently in the target directory."
    )

    parser.add_argument(
        '--download-query',
        action='store_true',
        help="Downloads query protein sequence in fasta format."
             " Will skip download if the same file exists currently in the target directory."
    )

    parser.add_argument(
        '--blast-dbs',
        action='store_true',
        help="Generates BLAST databases from genomes."
    )

    parser.add_argument(
        '--blast',
        action='store_true',
        help="Runs tBLASTn of provided protein accession sequence against genome databases."
    )

    parser.add_argument(
        '--orf-analyser',
        action='store_true',
        help="Runs ORF detection on BLAST hits."
    )

    parser.add_argument(
        '--hmmer',
        action='store_true',
        help="Runs HMMER domain filtering on BLAST hits."
    )

    parser.add_argument(
        '--rpsblast',
        action='store_true',
        help="Runs rpsblast of provided protein accession sequence against domain database."
    )

    parser.add_argument(
        '--rpsbproc',
        action='store_true',
        help="Runs rpsbproc to process the rpsblast output."
    )

    parser.add_argument(
        '--rpsbproc-parser',
        action='store_true',
        help="Parses the rpsbproc output to table format."
    )

    parser.add_argument(
        '--completeness-detector',
        action='store_true',
        help="Generates tile plot with highest-completeness degree per domain."
    )

    parser.add_argument(
        '--contingency-parser',
        action='store_true',
        help="Generates contingency tables and plots."
    )

    parser.add_argument(
        '--skip-validation', '-skp',
        action='store_true',
        help='Skip input validation.'
    )

    args, unknown = parser.parse_known_args()

    # -----------------------------
    # DEFINE SCRIPT EXECUTION PATH
    # -----------------------------
    script_dir = Path(__file__).resolve().parent / 'workflow'

    # -----------------------------
    # EXECUTE MAIN PIPELINE
    # -----------------------------
    main_cmd: list = [sys.executable, 'scripts/rpsHunter.py']

    if args.skip_validation:
        main_cmd.append('--skip-validation')

    if args.setup_databases:
        main_cmd.append('--setup-databases')

    if args.download_genomes:
        main_cmd.append('--download-genomes')

    if args.download_query:
        main_cmd.append('--download-query')

    if args.blast_dbs:
        main_cmd.append('--blast-dbs')

    if args.blast:
        main_cmd.append('--blast')

    if args.orf_analyser:
        main_cmd.append('--orf-analyser')

    if args.hmmer:
        main_cmd.append('--hmmer')

    if args.rpsblast:
        main_cmd.append('--rpsblast')

    if args.rpsbproc:
        main_cmd.append('--rpsbproc')

    if args.rpsbproc_parser:
        main_cmd.append('--rpsbproc-parser')

    if args.completeness_detector:
        main_cmd.append('--completeness-detector')

    if args.contingency_parser:
        main_cmd.append('--contingency-parser')

    if unknown:
        main_cmd.extend(unknown)

    result = subprocess.run(main_cmd, cwd=script_dir)
    sys.exit(result.returncode)
